spring:
  application:
    name: department-service
  cloud:
    config:
      uri: http://localhost:8088
  config:
    import: "optional:configserver:http://localhost:8088"
  datasource:
    url: jdbc:h2:file::./data/department-db
    username: sa
    password:
    driver-class-name: org.h2.Driver
    dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  zipkin:
    baseUrl: http://localhost:9411


#spring:
#  application:
#    name: department-service
#  config:
#    import: "configserver:http://localhost:8088"