spring:
  application:
    name: employee-service
  cloud:
    config:
      uri: http://localhost:8088
  config:
    import: "optional:configserver:http://localhost:8088"
  datasource:
    url: jdbc:h2:file::./data/employee-db
    username: sa
    password:
    driver-class-name: org.h2.Driver
    dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update